/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MatrimonyRouteImport } from './routes/matrimony'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as InboxChatIdRouteImport } from './routes/inbox.$chatId'
import { Route as PostPostIdMapRouteImport } from './routes/post.$postId.map'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrimonyRoute = MatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxChatIdRoute = InboxChatIdRouteImport.update({
  id: '/inbox/$chatId',
  path: '/inbox/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdMapRoute = PostPostIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => PostPostIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/matrimony': typeof MatrimonyRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/inbox/$chatId': typeof InboxChatIdRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/inbox/': typeof InboxIndexRoute
  '/post/$postId/map': typeof PostPostIdMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/matrimony': typeof MatrimonyRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/inbox/$chatId': typeof InboxChatIdRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/inbox': typeof InboxIndexRoute
  '/post/$postId/map': typeof PostPostIdMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/matrimony': typeof MatrimonyRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/inbox/$chatId': typeof InboxChatIdRoute
  '/post/$postId': typeof PostPostIdRouteWithChildren
  '/inbox/': typeof InboxIndexRoute
  '/post/$postId/map': typeof PostPostIdMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/matrimony'
    | '/notifications'
    | '/permissions'
    | '/profile'
    | '/search'
    | '/settings'
    | '/inbox/$chatId'
    | '/post/$postId'
    | '/inbox/'
    | '/post/$postId/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/matrimony'
    | '/notifications'
    | '/permissions'
    | '/profile'
    | '/search'
    | '/settings'
    | '/inbox/$chatId'
    | '/post/$postId'
    | '/inbox'
    | '/post/$postId/map'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create'
    | '/matrimony'
    | '/notifications'
    | '/permissions'
    | '/profile'
    | '/search'
    | '/settings'
    | '/inbox/$chatId'
    | '/post/$postId'
    | '/inbox/'
    | '/post/$postId/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  MatrimonyRoute: typeof MatrimonyRoute
  NotificationsRoute: typeof NotificationsRoute
  PermissionsRoute: typeof PermissionsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  InboxChatIdRoute: typeof InboxChatIdRoute
  PostPostIdRoute: typeof PostPostIdRouteWithChildren
  InboxIndexRoute: typeof InboxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrimony': {
      id: '/matrimony'
      path: '/matrimony'
      fullPath: '/matrimony'
      preLoaderRoute: typeof MatrimonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$chatId': {
      id: '/inbox/$chatId'
      path: '/inbox/$chatId'
      fullPath: '/inbox/$chatId'
      preLoaderRoute: typeof InboxChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId/map': {
      id: '/post/$postId/map'
      path: '/map'
      fullPath: '/post/$postId/map'
      preLoaderRoute: typeof PostPostIdMapRouteImport
      parentRoute: typeof PostPostIdRoute
    }
  }
}

interface PostPostIdRouteChildren {
  PostPostIdMapRoute: typeof PostPostIdMapRoute
}

const PostPostIdRouteChildren: PostPostIdRouteChildren = {
  PostPostIdMapRoute: PostPostIdMapRoute,
}

const PostPostIdRouteWithChildren = PostPostIdRoute._addFileChildren(
  PostPostIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  MatrimonyRoute: MatrimonyRoute,
  NotificationsRoute: NotificationsRoute,
  PermissionsRoute: PermissionsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  InboxChatIdRoute: InboxChatIdRoute,
  PostPostIdRoute: PostPostIdRouteWithChildren,
  InboxIndexRoute: InboxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
